#!/usr/bin/env node

/**
 * Script para gerar firebase-config.js a partir de variáveis de ambiente
 * Execute: node scripts/generate-config.js
 */

const fs = require('fs');
const path = require('path');

// Verificar se o arquivo .env existe
const envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
    console.error('❌ Arquivo .env não encontrado!');
    console.log('📝 Crie um arquivo .env na raiz do projeto com suas chaves do Firebase.');
    console.log('📋 Use o arquivo firebase-config.example.js como referência.');
    process.exit(1);
}

// Carregar variáveis de ambiente
require('dotenv').config();

// Verificar se todas as variáveis necessárias estão definidas
const requiredVars = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID'
];

const missingVars = requiredVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0) {
    console.error('❌ Variáveis de ambiente faltando:');
    missingVars.forEach(varName => {
        console.error(`   - ${varName}`);
    });
    process.exit(1);
}

// Gerar o conteúdo do arquivo de configuração
const configContent = `// Firebase Configuration - Generated automatically
// DO NOT EDIT THIS FILE MANUALLY - Use scripts/generate-config.js

const firebaseConfig = {
    apiKey: "${process.env.FIREBASE_API_KEY}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
    projectId: "${process.env.FIREBASE_PROJECT_ID}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${process.env.FIREBASE_APP_ID}",
    measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || ''}"
};

// Make it available globally
window.firebaseConfig = firebaseConfig;

// Export for Node.js environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = firebaseConfig;
}
`;

// Escrever o arquivo
const outputPath = path.join(__dirname, '..', 'js', 'firebase-config.js');
fs.writeFileSync(outputPath, configContent);

console.log('✅ firebase-config.js gerado com sucesso!');
console.log('🔒 Suas chaves do Firebase estão protegidas no arquivo .env');
console.log('📁 Arquivo gerado em: js/firebase-config.js');
