#!/usr/bin/env node

/**
 * Script para gerar firebase-config.js a partir de variáveis de ambiente
 * Execute: node scripts/generate-config.js
 */

const fs = require('fs');
const path = require('path');

// Verificar se o arquivo .env existe
const envPath = path.join(__dirname, '..', '.env');
const isProduction = process.env.NODE_ENV === 'production' || process.env.VERCEL;

if (!fs.existsSync(envPath) && !isProduction) {
    console.error('❌ Arquivo .env não encontrado!');
    console.log('📝 Crie um arquivo .env na raiz do projeto com suas chaves do Firebase.');
    console.log('📋 Use o arquivo firebase-config.example.js como referência.');
    process.exit(1);
}

// Carregar variáveis de ambiente
require('dotenv').config();

// Verificar se todas as variáveis necessárias estão definidas
const requiredVars = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID'
];

const missingVars = requiredVars.filter(varName => !process.env[varName]);

if (missingVars.length > 0 && !isProduction) {
    console.error('❌ Variáveis de ambiente faltando:');
    missingVars.forEach(varName => {
        console.error(`   - ${varName}`);
    });
    process.exit(1);
}

// Em produção (Vercel), usar valores padrão se não estiverem definidos
if (isProduction && missingVars.length > 0) {
    console.log('⚠️  Executando em produção, usando configuração padrão...');
}

// Função para obter valor da variável ou usar padrão
function getEnvValue(varName, defaultValue = '') {
    return process.env[varName] || defaultValue;
}

// Gerar o conteúdo do arquivo de configuração
const configContent = `// Firebase Configuration - Generated automatically
// DO NOT EDIT THIS FILE MANUALLY - Use scripts/generate-config.js

const firebaseConfig = {
    apiKey: "${getEnvValue('FIREBASE_API_KEY', 'AIzaSyAvBppTLTDs8qALcOjSmQgZU_KoPODp1I0')}",
    authDomain: "${getEnvValue('FIREBASE_AUTH_DOMAIN', 'admoirmaozinho.firebaseapp.com')}",
    projectId: "${getEnvValue('FIREBASE_PROJECT_ID', 'admoirmaozinho')}",
    storageBucket: "${getEnvValue('FIREBASE_STORAGE_BUCKET', 'admoirmaozinho.firebasestorage.app')}",
    messagingSenderId: "${getEnvValue('FIREBASE_MESSAGING_SENDER_ID', '79331048689')}",
    appId: "${getEnvValue('FIREBASE_APP_ID', '1:79331048689:web:02506c8ddbdd3369f97d50')}",
    measurementId: "${getEnvValue('FIREBASE_MEASUREMENT_ID', 'G-4NF3N0878T')}"
};

// Make it available globally
window.firebaseConfig = firebaseConfig;

// Export for Node.js environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = firebaseConfig;
}
`;

// Escrever o arquivo
const outputPath = path.join(__dirname, '..', 'js', 'firebase-config.js');
fs.writeFileSync(outputPath, configContent);

console.log('✅ firebase-config.js gerado com sucesso!');

if (isProduction && missingVars.length > 0) {
    console.log('⚠️  Usando configuração padrão para produção');
} else {
    console.log('🔒 Suas chaves do Firebase estão protegidas no arquivo .env');
}

console.log('📁 Arquivo gerado em: js/firebase-config.js');
